import Foundation

enum ClipboardCapturePolicy {
    static let enabledKey = "clipboardHistoryEnabled"
    static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    static func shouldCapture(types: Set<String>, enabled: Bool) -> Bool {
        enabled && types.isDisjoint(with: sensitiveTypes)
    }
}

struct SessionSummary: Equatable, Sendable {
    var completedCount = 0
    var medianResponseMs: Int?
    var latestResponseMs: Int?

    init(metrics: [SessionMetricV1] = []) {
        let completed = metrics.filter { $0.outcome == "delivered" }
        completedCount = completed.count
        // endToEnd includes the time spent speaking; response begins at release.
        let responses = completed.compactMap { metric -> Int? in
            guard let end = metric.endToEndMs, let stop = metric.stopAtMs,
                  end >= stop else { return nil }
            return end - stop
        }
        latestResponseMs = responses.last
        let sorted = responses.sorted()
        if !sorted.isEmpty {
            let middle = sorted.count / 2
            medianResponseMs = sorted.count.isMultiple(of: 2)
                ? sorted[middle - 1] + (sorted[middle] - sorted[middle - 1]) / 2
                : sorted[middle]
        }
    }
}

struct LocalServiceHealth: Decodable, Sendable {
    let status: String
    let service: String
    let protocolVersion: Int

    enum CodingKeys: String, CodingKey {
        case status, service
        case protocolVersion = "protocol_version"
    }

    func isReady(expectedService: String) -> Bool {
        status == "ok" && service == expectedService && protocolVersion == 1
    }
}
